version: '3.3'
services:
  nginx:
    image: nginx-server:{TAG}
    build:
      context: .
    ports:
      - "80:80"
    networks:
      - main
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    restart: on-failure
networks:
  main:
    external:
      name : main-overlay
