version: '3.7'

services:

  nginx:
     image: nginx-server:${TAG}
     ports:
       - "80:80"
     networks:
       - main-overlay
     deploy:
      replicas: 1
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  main-overlay:
    external: true