version: '3.3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - main
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    restart: on-failure
networks:
  main:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
